# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Iosevka Nerd Font Mono Heavy

general {
    hide_cursor = true
    immediate_render = true
    fail_timeout = 3000
}

animations {
    enabled = false
}

background {
    path = $HOME/pictures/wallpapers/clouds.jpg
    blur_passes = 3
}

shape {
    size = 35%, 60%
    color = rgb(333333)
}

image {
    path = $HOME/pictures/shd.png
    border_size = 0
    position = 0, +75
    rounding = 0
    size = 600
}

input-field {
    monitor =
    size = 23%, 5%
    outline_thickness = 6
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(ff6d0e) 
    check_color = rgb(ff6d0e) 
    fail_color = rgb(ff0000) 

    font_color = rgb(ffffff)
    fade_on_empty = false
    rounding = 0
    fade_timeout = 0

    font_family = $font
    placeholder_text = AUTHENTICATE
    fail_text = ACCESS DENIED

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    #dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -22%
    halign = center
    valign = center
}
