name: ci
on: push
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6.0.2

      - name: Set up package manager
        uses: pnpm/action-setup@v5.0.0
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format-ci
